---
sidebar: sidebar 
permalink: task-login-copyandsync.html 
keywords: copy and sync, NetApp Copy and Sync, log in to Copy and Sync, NetApp BlueXP, BlueXP Copy and Sync, NetApp Console 
summary: Utilice la NetApp Console para iniciar sesión en NetApp Copy and Sync. 
---
= Inicie sesión en NetApp Copy and Sync
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilice la NetApp Console para iniciar sesión en NetApp Copy and Sync.

Para iniciar sesión en la consola, puedes usar tus credenciales del sitio de soporte de NetApp o puedes registrarte para un inicio de sesión en la nube de NetApp usando tu correo electrónico y una contraseña. https://docs.netapp.com/us-en/console-setup-admin/task-logging-in.html["Obtenga más información sobre cómo iniciar sesión"^].

NetApp Copy and Sync utiliza la gestión de acceso de identidad para controlar el acceso que tiene cada usuario a acciones específicas.

*Rol de NetApp Console requerido*: rol de administrador de la organización. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Obtenga más información sobre los roles de acceso a la NetApp Console"^].

.Pasos
. Abra un navegador web y vaya a https://console.netapp.com/["NetApp Console"^] .
+
Aparece la página de inicio de sesión de la NetApp Console .

. Inicie sesión en la consola.
. Desde la navegación izquierda de la consola, seleccione *Movilidad* > *Copiar y sincronizar*.

